oslo-crypto:
  stage: deploy
  tags:
    - frontend
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Deploy to the stablestakes admin server"
    - ssh-add <(echo "$ssh_key")
    - rm -rf .git
    - ssh -o StrictHostKeyChecking=no -vvv frontend@10.10.10.96  "cd /home/frontend/oslo-frontend ; git reset --hard ; git pull ; source ~/.nvm/nvm.sh; nvm use 18.12.1; npm install --force ; pm2 restart 0; exit"
  only:
    - main

oslo-crypto-aws:
  stage: deploy
  tags:
    - frontend-aws
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Deploy to the stablestakes admin server"
    - ssh-add <(echo "$aws_rsa_key")
    - rm -rf .git
    - ssh -o StrictHostKeyChecking=no -vvv ubuntu@35.174.81.50  "cd /home/ubuntu/oslo-frontend ; git reset --hard ; git pull ; source ~/.nvm/nvm.sh; nvm use 18.12.1; npm install --force ; pm2 restart 0; exit"
  only:
    - main